title: Jerome P. Ciarkowski
email: jerome.ciarkowski@gmail.com
description: >-
  /je-rome chur-kow-skee/ (noun) 
  1. An enthusiast of choice architecture, software engineering, 
  video games, bodybuilding, and distractions from the game of life
github_username: JeromeCiarkowski
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Detroit
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jerome P. Ciarkowski"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "/je-rome chur-kow-skee/ <br>(noun) <br>1. An enthusiast of <br>choice architecture, software engineering, video games, bodybuilding, and distractions from the game of life"
  links:
    - label: "Blog"
      icon: "fas fa-fw fa-pencil-alt"
      url: "https://jeromeciarkowski.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JeromeCiarkowski"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/jeromeciarkowski/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/jerome.ciarkowski/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UC5_Gvd-FRkYQO5Hjynnd-zQ"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: "https://steamcommunity.com/id/FelixBrewBaker"

footer:
  links:
    - label: "Blog"
      icon: "fas fa-fw fa-pencil-alt"
      url: "https://jeromeciarkowski.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JeromeCiarkowski"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/jeromeciarkowski/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/jerome.ciarkowski/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UC5_Gvd-FRkYQO5Hjynnd-zQ"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: "https://steamcommunity.com/id/FelixBrewBaker"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/